config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "closets#index"


  get "closets"             => "closets#index"
  get 'closets/new'         => "closets#new", as: :new_closet
  get 'closets/:id/edit'    => 'closets#edit', as: :edit_closet
  delete "closets/:id"      => "closets#destroy"

  get "clothes_items/:id"   => "clothes_items#show", as: :clothes_item

  get "closets/:id"          => "closets#show", as: :closet





  post 'closets' => "closets#create"

  patch 'closets/:id' => "closets#update"
  delete 'closets/:id' => "closets#destroy"




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/closet.rb
class Closet < ApplicationRecord
  has_many :clothes_items
end

app/models/clothes_item.rb
class ClothesItem < ApplicationRecord
  belongs_to :closet



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/closets_controller.rb
class ClosetsController < ApplicationController
  def index
    @closets = Closet.all
  end

  #

  # def index
  #   @closets = Closet.find(params[:id])
  # end



  def create
      closet_params = params.require(:closet).permit(:name, :image_url)

      @closet = Closet.new(closet_params)

      if @closet.save
         redirect_to @closet
      else
         render 'new'
      end
    end


  def show
    @closet = Closet.find(params[:id])
  end
  def edit
    @closet = Closet.find(params[:id])
  end

  def new
   @closet = Closet.new
  end

  def update
   @closet = Closet.find(params[:id])
   closet_params = params.require(:closet).permit(:name, :image_url)


   closet_params = params.require(:closet).permit(:name, :image_url)

   if @closet.update_attributes(closet_params)
     redirect_to @closet
   else
     render 'edit'
   end

 end


 end
   def destroy
     @closet = Closet.find(params[:id])
     @closet.destroy
     redirect_to closets_path
   end





  def show
    @closet = Closet.find(params[:id])

  end


end
 end

end

app/controllers/clothes_items_controller.rb
class ClothesItemsController < ApplicationController

  def show
    @clothes_item = ClothesItem.find(params[:id])
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/closets_helper.rb
module ClosetsHelper
end

app/helpers/clothes_items_helper.rb
module ClothesItemsHelper
end

app/views/closets/_form.html.erb
<h3>New Closet</h3>
<%= form_for @closet do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %>

  <%= f.submit (@closet.new_record? ? "Create" : "Update") %>

<% end %>

app/views/closets/edit.html.erb
<h1>Edit closet</h1>

<%= render "form" %>

app/views/closets/index.html.erb
<h1>Closets</h1>

<% @closets.each do |closet| %>
  <p><%= closet.name %></p>
  <p><%= image_tag closet.image_url %></p>
<<<<<<< HEAD
  <%= link_to "[Edit]", edit_closet_path(closet) %>
  <%= link_to "[Delete]", closet_path(closet), method: :delete,
  data: { confirm: "Are you sure?" }%>
<% end %>

<p><%= link_to "[New Closet]", new_closet_path %>

</p>
=======
  <%= link_to "[New]", new_closet_path(@closet.id) %>
  <%= link_to "[Edit]", edit_closet_path(@closet.id) %>
  <%= link_to "[Delete]", dinosaur_path(@dinosaur.id), method: :delete,
  data: { confirm: "Are you sure?" } %>
<% end %>
>>>>>>> 74d5529abdd6da236677aca5b6ec46248f27c440

app/views/closets/new.html.erb
<<<<<<< HEAD
<h1>New closet</h1>
=======
<h1>New Dinosaur</h1>
>>>>>>> 74d5529abdd6da236677aca5b6ec46248f27c440

<%= render "form" %>

app/views/closets/show.html.erb
<h1><%= @closet.name %> </h1>
<h3> In use: </h3>
<% @closet.clothes_items.each do |item| %>
  <% if item.in_use %>
  <%= link_to clothes_item_path(item) do %>
  <%= image_tag item.image_url %>
  <% end %>
 <% end %>
<% end %>

app/views/clothes_items/show.html.erb
<h1> <%= @clothes_item.name %> </h1>
<div class = "main">
<%= image_tag @clothes_item.image_url %>
<div class = "descriptions"
<h4> Style: <%= @clothes_item.style  %> </h6>
<h4> Season: <%= @clothes_item.season  %> </h6>
<h4> <%= @clothes_item.in_use  %> </h6>
<p> Description: <%= @clothes_item.description %> </p>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wardrobe</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>